### ISSUE TITLE
How project structure might be changed?

### ISSUE THREAD

**Issue by beleran** [lux400/crew-applications#7]
How you projects structure might be changed in order to provide better scalability and maintainability in case of growth?

**Comment by lux400** [comment]
I think for large project is better to keep actions/reducers in redux folder which is in a components folder and a shared redux folder that keeps actions and reducers that are used in all project. Also is to split components for 'dumb' (components folder) and 'smart' (containers folder).

**Comment by beleran** [comment]
@lux400 and in case if you have for example 200 components and 100 reducers that related to totally different plugins. Is there any way to make such codebase manageable and extendable?

**Comment by lux400** [comment]
@beleran we can split components by modules and use HOCs

**Comment by beleran** [comment]
Sounds good. Thank you
