### ISSUE TITLE
Why do you need full REST client here?

### ISSUE THREAD

**Issue by beleran** [lux400/crew-applications#8]
https://github.com/lux400/crew-applications/blob/5e0bef39c19df3cf8951fb01a625630d65b314bc/src/api/client.js#L36

**Comment by lux400** [comment]
removed unused methods in https://github.com/lux400/crew-applications/commit/94417619b4b5fb6a61dff64afc316c62dd726e93

**Comment by beleran** [comment]
Looks good, thank you
